# Generated by Django 3.0.8 on 2020-07-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200719_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extendeduser',
            options={'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
