# Generated by Django 3.0.8 on 2020-08-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200720_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
