# Generated by Django 3.0.8 on 2020-08-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_device_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
