# Generated by Django 3.0.8 on 2020-08-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200811_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_info',
            field=models.TextField(help_text='Device information'),
        ),
    ]
