# Generated by Django 3.0.8 on 2020-08-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200812_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heavy_machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis', models.CharField(max_length=300)),
                ('batch_capacity', models.CharField(max_length=300)),
                ('power', models.CharField(max_length=300)),
                ('mixing_drum', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='dev_im/')),
            ],
            options={
                'verbose_name_plural': 'Heavy Machines',
            },
        ),
        migrations.AlterField(
            model_name='device',
            name='im',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='dev_im/'),
        ),
    ]
