# Generated by Django 3.0.8 on 2020-08-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200813_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='heavy_machine',
            name='machine_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
