# Generated by Django 3.0.8 on 2020-08-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_heavy_machine_machine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='heavy_machine',
            name='drive',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='heavy_machine',
            name='speed',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='heavy_machine',
            name='wire_rope',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
